### ISSUE TITLE
Question marks exist

### ISSUE THREAD

**Issue by racecarburton** [Drew-Killeen/propresenter-chord-editor#4]
[Treasure-Chords.zip](https://github.com/Drew-Killeen/propresenter-chord-editor/files/14747245/Treasure-Chords.zip)

**Comment by racecarburton** [comment]
[Something Good-Chords.zip](https://github.com/Drew-Killeen/propresenter-chord-editor/files/14747263/Something.Good-Chords.zip)

**Comment by racecarburton** [comment]
[House of the Lord-Chords.zip](https://github.com/Drew-Killeen/propresenter-chord-editor/files/14747290/House.of.the.Lord-Chords.zip)

**Comment by racecarburton** [comment]
[Sunday Is Coming.zip](https://github.com/Drew-Killeen/propresenter-chord-editor/files/14747574/Sunday.Is.Coming.zip)
Corresponding line breaks are also missing.

**Comment by Drew-Killeen** [comment]
Fixed with commit db21382
